## 讲解

In [36]:
import numpy as np

In [62]:
c = np.random.randn(3,3)
print(c)

d = np.random.randn(3,3)
print(d)

[[-0.02461696 -0.77516162  1.27375593]
 [ 1.96710175 -1.85798186  1.23616403]
 [ 1.62765075  0.3380117  -1.19926803]]
[[ 0.86334532 -0.1809203  -0.60392063]
 [-1.23005814  0.5505375   0.79280687]
 [-0.62353073  0.52057634 -1.14434139]]


In [66]:
# seed( ) 用于指定随机数生成时所用算法开始的整数值，
# 如果使用相同的seed( )值，则每次生成的随即数都相同，
# 如果不设置这个值，则系统根据时间来自己选择这个值，
# 此时每次生成的随机数因时间差异而不同。
np.random.seed(1)
c = np.random.randn(3,3)
print(c)

d = np.random.randn(3,3)
print(d)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[-0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842]]


In [52]:
x = np.array([[1, 2], [3, 4]])

flatten_X = x.flatten()
print(flatten_X)

flatten_X[1] = 1
print(flatten_X)
print(x)

ravel_X = x.ravel()
print(ravel_X)

ravel_X[1] = 1
print(ravel_X)
print(x)



[1 2 3 4]
[1 1 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[1 1 3 4]
[[1 1]
 [3 4]]


In [49]:
from sklearn import datasets

In [33]:
iris = datasets.load_iris()

iris_X = iris.data
iris_y = iris.target
print(iris_X)
print(iris_y)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [60]:
c = np.random.randn(3,4)
print(c.shape)
print(c)
print(np.sum(c, axis=1, keepdims=True))

(3, 4)
[[ 1.19891788  0.18515642 -0.37528495 -0.63873041]
 [ 0.42349435  0.07734007 -0.34385368  0.04359686]
 [-0.62000084  0.69803203 -0.44712856  1.2245077 ]]
[[ 0.37005894]
 [ 0.2005776 ]
 [ 0.85541033]]
