## 讲解

In [2]:
import numpy as np

In [3]:
a = np.arange(6).reshape((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [4]:
a = np.arange(6).reshape((3, -1))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
c = np.random.randint(0, 10, size=(3,3))
print(c)

reshape_F = np.reshape(c, (9, 1), order='F')
print(reshape_F)


reshape_C = np.reshape(c, (9, 1), order='C')
print(reshape_C)


[[8 5 4]
 [3 2 2]
 [7 5 6]]
[[8]
 [3]
 [7]
 [5]
 [2]
 [5]
 [4]
 [2]
 [6]]
[[8]
 [5]
 [4]
 [3]
 [2]
 [2]
 [7]
 [5]
 [6]]


In [10]:
import time

x1 = np.random.randint(0, 10, size=(10000, 1))
x2 = np.random.randint(0, 10, size=(10000, 1))

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1.T,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = [202528]
 ----- Computation time = 20.757437000000103ms
dot = [[202528]]
 ----- Computation time = 0.16086900000011894ms


In [19]:
x3 = np.random.randint(0, 10, size=(3, 3))
print(x3)
x3[0:3,0]

[[4 1 6]
 [0 2 5]
 [2 1 4]]


array([4, 0, 2])

In [28]:
x4 = np.random.randint(0, 10, size=(3, 3, 3))
print(x4)
x4[0:3, 0 :3, 0:2]

[[[8 7 1]
  [9 2 2]
  [5 0 9]]

 [[8 8 5]
  [1 7 4]
  [7 5 4]]

 [[7 9 8]
  [2 3 9]
  [9 3 1]]]


array([[[8, 7],
        [9, 2],
        [5, 0]],

       [[8, 8],
        [1, 7],
        [7, 5]],

       [[7, 9],
        [2, 3],
        [9, 3]]])

In [46]:
x = np.array([[[0], [1], [2]]])
print(x)

print(x.shape)

print(np.squeeze(x))

print(np.squeeze(x, axis=0))

[[[0]
  [1]
  [2]]]
(1, 3, 1)
[0 1 2]
[[0]
 [1]
 [2]]
