In [35]:
import numpy as np 

# this is header
##123


In [36]:
V = [1,2,3]
U = np.exp(V)
print(U)

[  2.71828183   7.3890561   20.08553692]


In [33]:
V = np.random.rand(3,3)
print(V)
b = 2
out = V + 2
print(out)
out = V - 2
print(out)
out = V * 2
print(out)
out = V / 2
print(out)


[[ 0.31255674  0.09385136  0.26955278]
 [ 0.88494633  0.21524468  0.93963532]
 [ 0.43713214  0.70136132  0.11698503]]
[[ 2.31255674  2.09385136  2.26955278]
 [ 2.88494633  2.21524468  2.93963532]
 [ 2.43713214  2.70136132  2.11698503]]
[[-1.68744326 -1.90614864 -1.73044722]
 [-1.11505367 -1.78475532 -1.06036468]
 [-1.56286786 -1.29863868 -1.88301497]]
[[ 0.62511347  0.18770272  0.53910556]
 [ 1.76989266  0.43048936  1.87927064]
 [ 0.87426427  1.40272265  0.23397005]]
[[ 0.15627837  0.04692568  0.13477639]
 [ 0.44247316  0.10762234  0.46981766]
 [ 0.21856607  0.35068066  0.05849251]]


In [34]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
cal = A.sum(axis = 0)
print('cal')
print(cal)
per = 100 * A / cal.reshape(1, 4)
print('per:')
print(per)

cal
[  59.   239.   155.4   76.9]
per:
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]
